### ISSUE TITLE
New Coin Selection Algorithm

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#120]
Well, I went deep into a rabbit hole while looking at Core's algorithm, so here's what I found:

There are four major algorithms used by various implementations:
1. Highest Priority first (bitcoinj)
2. Oldest first (Electrum)
3. Pruned Oldest First (Mycelium)
4. Target sized Change (Electrum)

Core, is however a bit more complex system which either tries for an exact match, falls back to a knapsack problem and then worst case, there's the const change one with 0.01 btc as const change.

Core is looking at migrating to a better algorithm detailed over at https://github.com/bitcoin/bitcoin/pull/10637 (overkill at the moment).

I'm guessing that any one of the first four would be sufficient for our use case right now. I'll look more into this and put in a PR for the most appropriate one.

**Comment by adiabat** [comment]
My thoughts on this:

I'd say 1 and 2 don't make much sense.  "Priority" has been removed from the bitcoind mining selection code for well over a year.  "Oldest first" sounds like a rough proxy for priority, so also doesn't make sense.  Current mining code doesn't care how old inputs are, they only care about getting lots of fees.

Not sure what the difference is between 2 and 3, can look.  4 might make sense to copy some ideas from.

Currently the code sorts by utxo value, then strips off overly high values.  It also sorts unconfirmed to the bottom of the list, but still allows selection from unconfirmed.  That might be a bad idea and it could instead not use unconfirmed utxos for inputs; that issue may be moot if switches to blocks-only, which it probably should since it's SPV.

**Comment by Varunram** [comment]
Agree, electrum has a weird combination of 2 and 4, should look more into that. The difference between 2&3 is that in three, the small(er) utxos are pruned, nothing special other than that.

**Comment by Varunram** [comment]
I don't think this is a priority right now since the PR I made a long while towards a few improvements was closed. Also, this isn't off the top important since we need to focus on protocol level improvements first.
