### ISSUE TITLE
Pruned node

### ISSUE THREAD

**Issue by karel-3d** [mit-dci/lit#151]
Hello,

does lit work with pruned node?

All the other three lightning implementations require non-pruned node.

**Comment by Varunram** [comment]
@karel-3d I don't think we're there yet, we do rely on block advertising nodes to sync lit. (Correct me if I'm wrong, as far as I tested, didn't seem to work). Although on testnet, since we start sync from block 1256000 (on testnet), if a pruned node has that in memory, it should be able to sync just fine.

**Comment by adiabat** [comment]
lit currently works with randomly selected full nodes by doing an SPV-type sync.  There are other modules like powless that allow it to connect to a web API.  A non-pruned node is not required.
