### ISSUE TITLE
boltdb performance

### ISSUE THREAD

**Issue by navybluesilver** [mit-dci/lit#285]
Is boltdb part of the strategic solution or are we planning to replace it at a later point in time by something else? The performance is bad when a node has more than 10 dlc contracts (it gets worse after creating even more contracts)

If we do plan to replace it with something else, please let me know which database technology... Maybe I can help with the implementation.

**Comment by Varunram** [comment]
@navybluesilver boltdb isn't part of any strategic solution, we chose it because it was easy to start off requiring minimal overhead. We'd be open to replacing it with any superior implementation (at least equal to boltdb's characteristics) but you should avoid badgerDB since we tried that out for something and it didn't work out that well.

**Comment by adiabat** [comment]
I've been using goleveldb (https://github.com/syndtr/goleveldb) and it seems to work pretty well and has faster writes than boltdb.  I don't think it'd be much work to switch to that, as they're quite similar.  The main change is that leveldb doesn't have buckets, so we could switch to key prefixes instead of buckets.

**Comment by delbonis** [comment]
Would it be bad to just have multiple leveldb databases?  And that way if one gets corrupted it's not *as* big a deal.

**Comment by navybluesilver** [comment]
It is actually not the database that was causing the issue, but the fact that the contracts had to store/communicate too many signatures.

**Comment by delbonis** [comment]
(Related: to revise my comment earlier, I meant have multiple separate instances of leveldb for different purposes, and that would also avoid a prefix scheme)

**Comment by delbonis** [comment]
We can come back to this later if it's an issue, closing for now.
